services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mailer
      POSTGRES_USER: mailer
      POSTGRES_PASSWORD: mailer
    ports: [ "5432:5432" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailer -d mailer"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports: [ "5672:5672", "15672:15672" ]

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports: [ "16686:16686", "4317:4317" ]

  seq:
    image: datalust/seq:latest
    environment: { ACCEPT_EULA: "Y" }
    ports: [ "5341:80" ]

  api:
    build: { context: ., dockerfile: src/EmailService.Api/Dockerfile }
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=mailer;Username=mailer;Password=mailer
      RabbitMq__Host: rabbitmq
      RabbitMq__User: guest
      RabbitMq__Pass: guest
      OpenTelemetry__OtlpEndpoint: http://jaeger:4317
    depends_on: [ postgres, rabbitmq, jaeger ]
    ports: [ "8080:8080" ]

  worker:
    build: { context: ., dockerfile: src/EmailService.Worker/Dockerfile }
    environment:
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=mailer;Username=mailer;Password=mailer
      RabbitMq__Host: rabbitmq
      RabbitMq__User: guest
      RabbitMq__Pass: guest
      OpenTelemetry__OtlpEndpoint: http://jaeger:4317
    depends_on: [ postgres, rabbitmq, jaeger ]
